//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.sforce.com/2005/09/outbound", ConfigurationName="NotificationPort")]
public interface NotificationPort
{
    
    // CODEGEN: Generating message contract since the operation notifications is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(sObject))]
    notificationsResponse1 notifications(notificationsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<notificationsResponse1> notificationsAsync(notificationsRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2005/09/outbound")]
public partial class notifications
{
    
    private string organizationIdField;
    
    private string actionIdField;
    
    private string sessionIdField;
    
    private string enterpriseUrlField;
    
    private string partnerUrlField;
    
    private OpportunityNotification[] notificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string OrganizationId
    {
        get
        {
            return this.organizationIdField;
        }
        set
        {
            this.organizationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string ActionId
    {
        get
        {
            return this.actionIdField;
        }
        set
        {
            this.actionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string SessionId
    {
        get
        {
            return this.sessionIdField;
        }
        set
        {
            this.sessionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string EnterpriseUrl
    {
        get
        {
            return this.enterpriseUrlField;
        }
        set
        {
            this.enterpriseUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string PartnerUrl
    {
        get
        {
            return this.partnerUrlField;
        }
        set
        {
            this.partnerUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Notification", Order=5)]
    public OpportunityNotification[] Notification
    {
        get
        {
            return this.notificationField;
        }
        set
        {
            this.notificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/2005/09/outbound")]
public partial class OpportunityNotification
{
    
    private string idField;
    
    private Opportunity sObjectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public Opportunity sObject
    {
        get
        {
            return this.sObjectField;
        }
        set
        {
            this.sObjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sobject.enterprise.soap.sforce.com")]
public partial class Opportunity : sObject
{
    
    private System.Nullable<double> amountField;
    
    private bool amountFieldSpecified;
    
    private string products_Of_Interest__cField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public System.Nullable<double> Amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AmountSpecified
    {
        get
        {
            return this.amountFieldSpecified;
        }
        set
        {
            this.amountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Products_Of_Interest__c
    {
        get
        {
            return this.products_Of_Interest__cField;
        }
        set
        {
            this.products_Of_Interest__cField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Opportunity))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AggregateResult))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sobject.enterprise.soap.sforce.com")]
public partial class sObject
{
    
    private string[] fieldsToNullField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fieldsToNull", IsNullable=true, Order=0)]
    public string[] fieldsToNull
    {
        get
        {
            return this.fieldsToNullField;
        }
        set
        {
            this.fieldsToNullField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sobject.enterprise.soap.sforce.com")]
public partial class AggregateResult : sObject
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:sobject.enterprise.soap.sforce.com", Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/2005/09/outbound")]
public partial class notificationsResponse
{
    
    private bool ackField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool Ack
    {
        get
        {
            return this.ackField;
        }
        set
        {
            this.ackField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class notificationsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sforce.com/2005/09/outbound", Order=0)]
    public notifications notifications;
    
    public notificationsRequest()
    {
    }
    
    public notificationsRequest(notifications notifications)
    {
        this.notifications = notifications;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class notificationsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sforce.com/2005/09/outbound", Order=0)]
    public notificationsResponse notificationsResponse;
    
    public notificationsResponse1()
    {
    }
    
    public notificationsResponse1(notificationsResponse notificationsResponse)
    {
        this.notificationsResponse = notificationsResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface NotificationPortChannel : NotificationPort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NotificationPortClient : System.ServiceModel.ClientBase<NotificationPort>, NotificationPort
{
    
    public NotificationPortClient()
    {
    }
    
    public NotificationPortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NotificationPortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotificationPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotificationPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    notificationsResponse1 NotificationPort.notifications(notificationsRequest request)
    {
        return base.Channel.notifications(request);
    }
    
    public notificationsResponse notifications(notifications notifications1)
    {
        notificationsRequest inValue = new notificationsRequest();
        inValue.notifications = notifications1;
        notificationsResponse1 retVal = ((NotificationPort)(this)).notifications(inValue);
        return retVal.notificationsResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<notificationsResponse1> NotificationPort.notificationsAsync(notificationsRequest request)
    {
        return base.Channel.notificationsAsync(request);
    }
    
    public System.Threading.Tasks.Task<notificationsResponse1> notificationsAsync(notifications notifications)
    {
        notificationsRequest inValue = new notificationsRequest();
        inValue.notifications = notifications;
        return ((NotificationPort)(this)).notificationsAsync(inValue);
    }
}
